
master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0


image:
  registry: docker.io
  repository: bitnamilegacy/elasticsearch
  tag: 9.1.2-debian-12-r0
  pullPolicy: IfNotPresent


ingress:
  enabled: true
  hostname: elastic.kube.lan
  ingressClassName: nginx
